#========================================================================#
#  JXPAMG(IAPCM & XTU Parallel Algebraic Multigrid) (c) 2009-2013        #
#  Institute of Applied Physics and Computational Mathematics            #
#  School of Mathematics and Computational Science Xiangtan University   #
#  peghoty@163.com   (Zhou Zhiyang)                                      #
#  xwxu@iapcm.ac.cn  (Xu Xiaowen)                                        #
#  yuexq1111@163.com (Yue Xiaoqiang)                                     #
#========================================================================#

# Created by peghoty 2011/09/022
# Modified by Yue Xiaoqiang on 2012/10/22
# Modified by mrz on 2023/4/9

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# JXPAMG directory and MPI diectory
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

JXPAMGDIR  = /vol8/home/xtu_pcy/l_s/MxP-JXPAMG/jxpamg-basic-D

JXPAMG_USE_MPI = YES
ifdef JXPAMG_USE_MPI
MPIDIR    = /vol8/appsoftware/mpi-x
endif

#天河 hthreads 路径++++++++++++++++++++++++++++++++++++++++++++++++++
HT_ROOT   = /vol8/appsoftware/mt3000_programming_env/hthreads

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# Use the OpenMP parallelism [YES] or not [#YES]
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
JXPAMG_USE_OMP = YES

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# Use big-int and big-double structures [YES] or not [#YES]
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
JX_USE_BIG_INT = #YES
JX_USE_BIG_DOUBLE = #YES
JX_USE_COMPLEX = #YES

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# Add debug compiler opention  
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
DEBUG_OPTION = #YES

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# Use MUMPS as the coarsest solver [YES] or not [#YES]
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
JX_USE_MUMPS = #YES
ifdef JX_USE_MUMPS
topdir = /home/yuexq/MUMPS_4.10.0
endif

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# Use LAPACK as the air coarse [YES] or not [#YES]
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
JX_USE_LAPACK = #YES

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# About hwloc
# NOTICE: Setting USING_HWLOC to 'no' will result in the shutdown of 
#         JX_REODER_SEND_RECV and JX_hoAllreduce
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
USING_HWLOC = #YES 
HWLOC_DIR	= #HWLOC_DIR

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# reoder send and recv
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
JX_REODER_SEND_RECV = #YES
JX_REODER_SEND_CLOSER = #YES
JX_REODER_RECV_CLOSER = #YES

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# Optimization of Version 2.0.2
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
JX_MiniBranRAP = YES
JX_SplitRAP = #YES
JX_hoAllreduce = #YES

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# suffixes
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
.SUFFIXES:.c .f90 .f .for
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# compiler
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
ifdef JXPAMG_USE_MPI

ifdef JXPAMG_USE_OMP
FC = $(MPIDIR)/bin/mpif90 -fopenmp
CC = $(MPIDIR)/bin/mpicc -fopenmp
else
FC = $(MPIDIR)/bin/mpif90
CC = $(MPIDIR)/bin/mpicc
endif
else
ifdef JXPAMG_USE_OMP
FC = gfortran -fopenmp
CC = gcc -fopenmp
else
FC = gfortran
CC = gcc
endif
endif

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# compile option
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
DEST := /usr/local/jxpamg-1.1

ifdef JXPAMG_USE_MPI
JX_MPI_CP_OPTION = -DJX_USING_MPI=1
else
JX_MPI_CP_OPTION = -DJX_USING_MPI=0
endif

ifdef JXPAMG_USE_OMP
JX_OMP_CP_OPTION = -DJX_USING_OPENMP=1
else
JX_OMP_CP_OPTION = -DJX_USING_OPENMP=0
endif

ifdef JX_USE_BIG_INT
JX_BIG_INT_OPTION = -DJX_USING_BIG_INT=1
else
JX_BIG_INT_OPTION = -DJX_USING_BIG_INT=0
endif

ifdef JX_USE_BIG_DOUBLE
JX_BIG_DOUBLE_OPTION = -DJX_USING_BIG_DOUBLE=1
else
JX_BIG_DOUBLE_OPTION = -DJX_USING_BIG_DOUBLE=0
endif

ifdef JX_USE_MUMPS
JX_MUMPS_OPTION = -DJX_USING_MUMPS=1
libdir = $(topdir)/lib
include $(topdir)/Makefile.inc
MUMPS_INCLUDE_O = $(INCS)
MUMPS_INCLUDE_T = -I$(topdir)/include
MUMPS_INCLUDES = $(MUMPS_INCLUDE_O) $(MUMPS_INCLUDE_T)
MUMPS_LIB_O = -L$(libdir) -ldmumps
MUMPS_LIB_T = -L$(libdir) -lmumps_common
MUMPS_LIBS = $(MUMPS_LIB_O) $(MUMPS_LIB_T) $(LORDERINGS) $(LIBS) $(LIBOTHERS)
else
JX_MUMPS_OPTION = -DJX_USING_MUMPS=0
endif

ifdef JX_USE_COMPLEX
override JX_User_Optional_Parameters += -DJX_USING_COMPLEX=1
endif

ifdef USING_HWLOC

ifdef JX_REODER_SEND_RECV
override JX_User_Optional_Parameters += -DJX_REODER_SEND_RECV=1
ifdef JX_REODER_SEND_CLOSER
override JX_User_Optional_Parameters += -DJX_REODER_SEND_CLOSER=1 
endif
ifdef JX_REODER_RECV_CLOSER
override JX_User_Optional_Parameters += -DJX_REODER_RECV_CLOSER=1 
endif
else
override JX_User_Optional_Parameters += -DJX_REODER_SEND_RECV=0
endif

ifdef JX_hoAllreduce
override JX_User_Optional_Parameters += -DJX_hoAllreduce=1
endif

endif


ifdef JX_MiniBranRAP
override JX_User_Optional_Parameters += -DJX_MiniBranRAP=1
endif


ifdef JX_SplitRAP
override JX_User_Optional_Parameters += -DJX_SplitRAP=1
endif

ifdef DEBUG_OPTION
override C_COMPILE_OPTION += -g
override F_COMPILE_OPTION += -g
override C_COMPILE_FLAGS += -g
override F_COMPILE_FLAGS += -g
endif

override C_COMPILE_OPTION += -O2 -Wall ${JX_MPI_CP_OPTION}  ${JX_OMP_CP_OPTION} ${JX_BIG_INT_OPTION} ${JX_BIG_DOUBLE_OPTION} ${JX_User_Optional_Parameters}
override F_COMPILE_OPTION += -O2 -Wall
CDEFS  =
FDEFS  = ${CDEFS}

override C_COMPILE_FLAGS += -fPIC -O2 -Wall
override F_COMPILE_FLAGS += -fPIC -O2 -Wall

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# include
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
JXPAMGINCLUDES = -I ${JXPAMGDIR}/include -I ${JXPAMGDIR}/fv_amg/include
ifdef JXPAMG_USE_MPI
MPIINCLUDES    = -I ${MPIDIR}/include
endif
ifdef USING_HWLOC
HWLOCINCLUDES    = -I ${HWLOC_DIR}/include
endif

HTINCLUDES     = -I $(HT_ROOT)/include  
BEIDOUDIR    = /vol8/home/xtu_pcy/l_s/BeidouBLAS_unified
PANGULU_DIR  = /vol8/home/xtu_pcy/l_s/pangulu/pangulu2/pangulu-20251020--/final_test/PanguLU-mixprecision
ENV_DIR      = /vol8/home/xtu_pcy/l_s/pangulu/pangulu2/pangulu-20251020--/final_test/PanguLU_env
PANGULU_INCLUDES = -I $(PANGULU_DIR)/include -I $(PANGULU_DIR)/examples
PANGULU_LIB  = $(PANGULU_DIR)/lib/libpangulu.a $(ENV_DIR)/lib/libopenblas.a $(ENV_DIR)/lib/libmetis.a $(ENV_DIR)/lib/libGKlib.a
AllCINCLUDES   = ${JXPAMGINCLUDES} ${MPIINCLUDES} ${BEIDOUBLASINCLUDES} ${PANGULU_INCLUDES} ${HWLOCINCLUDES} ${HTINCLUDES}
BEIDOUBLASINCLUDES = -I ${BEIDOUDIR}/include -I ${BEIDOUDIR}/dsp/spgemm_include -I $(JXPAMGDIR)/beidoublasgemm

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# basic libs
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
MATHLIB = -lm
CPPLIB  = -lstdc++
BEIDOUBLASLIB = -L ${BEIDOUDIR}/lib -lbeidouBLAS
ifdef JX_USE_MUMPS
BLAS_LIB = -lblas
endif

ifdef JX_USE_LAPACK
LAPACK_LIB = -llapack
endif

ifdef JXPAMG_USE_MPI
#mpich
#MPILIB  = -L ${MPIDIR}/lib -lmpich
#openmpi
MPILIB  = -L ${MPIDIR}/lib -lmpi
endif
ifdef USING_HWLOC
HWLOCLIB = -L ${HWLOC_DIR}/lib -lhwloc
endif

HTLIB = -L $(HT_ROOT)/lib -lhthread_host

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# libs for building jxpamg lib
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
LIBS2JXPAMG = ${MPILIB} ${MATHLIB} ${CPPLIB}

CFLAGS = ${CDEFS} ${C_COMPILE_OPTION} ${AllCINCLUDES} ${LIBS2JXPAMG}
FFLAGS = ${FDEFS} ${F_COMPILE_OPTION} ${AllCINCLUDES} ${LIBS2JXPAMG}

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# rules for compiling the source files
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
.c.o:
	${CC} -o $@ -c ${CFLAGS} $<
.f.o:
	${FC} -o $@ -c ${FFLAGS} $<
.for.o:
	${FC} -o $@ -c ${FFLAGS} $<
.f90.o:
	${FC} -o $@ -c ${FFLAGS} $<

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# all libs for running programs
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
JXPAMGLIB  = -L ${JXPAMGDIR}/lib -lJXPAMG
ALLLIBS    =  ${JXPAMGLIB} ${LIBS2JXPAMG} ${PANGULU_LIB} -L ${BEIDOUDIR}/lib $(JXPAMGDIR)/beidoublasgemm/beidoublas_spgemm.o $(JXPAMGDIR)/spgemm_adapter.o -lbeidouBLAS ${HTLIB}
